spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/management-enrollment-db}
spring.data.mongodb.database=${MONGODB_DATABASE:management-enrollment-db}
#spring.jpa.properties.javax.persistence.validation.mode=none

# Allow overriding springdoc paths via env vars if desired
springdoc.api-docs.groups.enabled=${SPRINGDOC_GROUPS_ENABLED:true}
springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH:/swagger-doc/swagger-ui.html}
springdoc.api-docs.path=${SPRINGDOC_API_DOCS_PATH:/swagger-doc/v3/api-docs}

## MULTIPART (MultipartProperties)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB